version: '3'
services:
      db: 
          image:  'postgres:latest'
          environment:
                  POSTGRES_PASSWORD: 123
                  POSTGRES_USER: postgres
                  POSTGRES_DB: postgres
          volumes: 
              - ./pgdata:/var/lib/postgressql/data
          ports: 
              - "5432:5432"